version: '3'    
services:
    server:
        build: ./youselect-server
        container_name: youselect-server
        ports: 
            - 5500:5500
    client:
        build: ./youselect-client
        container_name: youselect-client
        ports: 
            - 80:3000
    db:
        image: mysql
        container_name: youselect-mysql
        environment:
            - MYSQL_ROOT_PASSWORD=secret